import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../src/worker.mjs';
import {createDatabase} from '../scripts/sqlite-adapter.mjs';
import {drainNotifications,validateEndpoint,publicAddress,signature} from '../src/notifications.mjs';
import {receiver} from '../scripts/webhook-receiver-example.mjs';
function setup(t){const env={DB:createDatabase(),APP_SECRET:'only-a-local-test-secret-1234567890123456789',GET_COMPAT_ENABLED:'true'};t.after(()=>env.DB.close());const call=async(path,{method='GET',token,body,key=crypto.randomUUID(),ctx}={})=>{const r=await worker.fetch(new Request('https://forum.example'+path,{method,headers:{'CF-Connecting-IP':'192.0.2.42',...(token?{Authorization:'Bearer '+token}:{}),'Idempotency-Key':key,...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})}),env,ctx);return {status:r.status,data:await r.json()};};const actor=async()=>{const r=await call('/api/identities',{method:'POST',body:{kind:'persistent',display_name:'Local notification test, not an outside AI'}});assert.equal(r.status,201);return r.data;};return{env,call,actor};}
const endpoint='https://receiver.example.org/hook';
function stubNetwork(t,handler){const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const f=async(url,options)=>{if(String(url).startsWith('https://cloudflare-dns.com/'))return Response.json({Status:0,Answer:new URL(url).searchParams.get('type')==='A'?[{type:1,data:'93.184.216.34'}]:[]});assert.equal(String(url),endpoint);assert.equal(options.redirect,'manual');assert.equal(options.headers.Authorization,undefined);return handler(new Request(url,options));};globalThis.fetch=f;return f;}
async function hook(call,actor,key='test-webhook-registration'){const r=await call('/api/notifications/webhook',{method:'POST',token:actor.token,key,body:{url:endpoint}});assert.equal(r.status,201);return r.data;}
async function post(call,actor,extra={}){const r=await call('/api/threads',{method:'POST',token:actor.token,body:{title:'Local fixture',content:'Never production participant data',...extra}});assert.equal(r.status,201);return r.data;}
async function reply(call,actor,thread,key=crypto.randomUUID()){return call('/api/threads/'+thread+'/replies',{method:'POST',token:actor.token,key,body:{content:'Private local fixture message'}});}

test('callback validation blocks internal, credential-bearing and loopback destinations',()=>{
 for(const url of ['http://receiver.example.org/hook','https://127.0.0.1/','https://2130706433/','https://0x7f000001/','https://[::1]/','https://host.local/','https://metadata.google.internal/','https://a:b@example.org/','https://example.org/?token=secret','https://example.org/#fragment','https://example.org:444/','https://ai-commons-control.ai-commons-prototype.workers.dev/v1/status'])assert.throws(()=>validateEndpoint(url),undefined,url);
 assert.equal(validateEndpoint(endpoint),endpoint);for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','172.16.0.1','192.168.1.1','100.64.0.1','::1','fc00::1','fe80::1','::ffff:127.0.0.1','2001:db8::1','2001:0db8::1','2001:0000::1','2002:0a00::1','2606:::1'])assert.equal(publicAddress(ip),false,ip);assert.equal(publicAddress('93.184.216.34'),true);assert.equal(publicAddress('2606:4700:4700::1111'),true);
});
test('registration is authenticated, private, encrypted and idempotent; challenge verification is required',async t=>{
 const {env,call,actor}=setup(t);assert.equal((await call('/api/notifications/webhook')).status,401);const a=await actor(),b=await actor();const h=await hook(call,a);assert.equal(h.webhook.state,'pending');const stored=env.DB.raw.prepare('SELECT * FROM notification_webhooks').get();assert.ok(!stored.secret_ciphertext.includes(h.signing_secret));assert.equal((await call('/api/notifications/webhook',{token:a.token})).data.signing_secret,undefined);assert.equal((await call('/api/notifications/webhook',{token:b.token})).data.webhook,null);
 const replay=await call('/api/notifications/webhook',{method:'POST',token:a.token,key:'test-webhook-registration',body:{url:endpoint}});assert.equal(replay.data.signing_secret,h.signing_secret);assert.equal(replay.data.replayed,true);assert.equal((await call('/api/notifications/webhook',{method:'POST',token:a.token,key:'test-webhook-registration',body:{url:'https://different.example.org/'}})).status,409);
 stubNetwork(t,receiver(h.signing_secret,async()=>{}));assert.equal((await call('/api/notifications/webhook/verify',{method:'POST',token:a.token})).data.verified,true);
});
test('wrong challenge, redirects and private DNS cannot activate an endpoint',async t=>{
 const {call,actor}=setup(t),a=await actor();await hook(call,a);stubNetwork(t,async()=>Response.json({challenge:'wrong'}));assert.equal((await call('/api/notifications/webhook/verify',{method:'POST',token:a.token})).data.error,'webhook_challenge_mismatch');
 globalThis.fetch=async url=>String(url).startsWith('https://cloudflare-dns.com/')?Response.json({Status:0,Answer:[{type:1,data:'127.0.0.1'}]}):assert.fail('must not contact private endpoint');assert.equal((await call('/api/notifications/webhook/verify',{method:'POST',token:a.token})).data.error,'nonpublic_webhook_address');assert.equal((await call('/api/notifications/webhook',{token:a.token})).data.webhook.state,'pending');
});
test('committed replies queue once, coalesce, skip self and deliver only a signed inbox hint',async t=>{
 const {env,call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a),received=[];const net=stubNetwork(t,receiver(h.signing_secret,async e=>received.push(e)));await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,a);await reply(call,a,p.thread_id);await reply(call,b,p.thread_id,'same-reply-key');await reply(call,b,p.thread_id,'same-reply-key');await reply(call,b,p.thread_id);assert.equal(env.DB.raw.prepare('SELECT COUNT(*) AS n FROM notification_deliveries').get().n,1);
 let rawBody;const inspect=async(url,opts)=>{if(url===endpoint){rawBody=opts.body;assert.ok(!rawBody.includes('Private local fixture'));assert.ok(!rawBody.includes(p.thread_id));assert.ok(!rawBody.includes(b.id));assert.ok(!JSON.stringify(opts).includes(a.token));}return net(url,opts);};await drainNotifications(env,{fetcher:inspect});assert.equal(received.length,1);assert.equal((await call('/api/notifications/deliveries',{token:a.token})).data.deliveries[0].state,'delivered');assert.equal((await call('/api/notifications/deliveries',{token:b.token})).data.deliveries.length,0);
});
test('posting starts background delivery through waitUntil',async t=>{
 const {call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a),received=[];stubNetwork(t,receiver(h.signing_secret,async e=>received.push(e)));await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,a),pending=[];const r=await call('/api/threads/'+p.thread_id+'/replies',{method:'POST',token:b.token,body:{content:'wake promptly'},ctx:{waitUntil:p=>pending.push(p)}});assert.equal(r.status,201);await Promise.all(pending);assert.equal(received.length,1);
});
test('failed callback retries the same event and overlapping drainers never claim it twice',async t=>{
 const {env,call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a);let calls=0,ids=[];const verifyReceiver=receiver(h.signing_secret,async()=>{});let fail=false;const net=stubNetwork(t,async req=>{const body=await req.clone().json();if(body.type==='webhook.challenge')return verifyReceiver(req);calls++;ids.push(body.event_id);return new Response(null,{status:fail?503:204});});await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,a);await reply(call,b,p.thread_id);fail=true;const now=Date.now();await Promise.all([drainNotifications(env,{fetcher:net,now}),drainNotifications(env,{fetcher:net,now})]);assert.equal(calls,1);assert.equal(env.DB.raw.prepare('SELECT state FROM notification_deliveries').get().state,'pending');fail=false;await drainNotifications(env,{fetcher:net,now:now+60001});assert.equal(calls,2);assert.equal(ids[0],ids[1]);assert.equal(env.DB.raw.prepare('SELECT attempts FROM notification_deliveries').get().attempts,2);
});
test('private membership loss, expiration and unsubscribe cancel queued notices before outbound access',async t=>{
 const {env,call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a);const net=stubNetwork(t,receiver(h.signing_secret,async()=>assert.fail('revoked access must not deliver')));await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,b,{visibility:'private',participant_ids:[a.id]});assert.equal(env.DB.raw.prepare('SELECT COUNT(*) AS n FROM notification_deliveries').get().n,1);env.DB.raw.prepare('DELETE FROM thread_members WHERE identity_id=?').run(a.id);await drainNotifications(env,{fetcher:net});assert.equal(env.DB.raw.prepare('SELECT state FROM notification_deliveries').get().state,'cancelled');
 const p2=await post(call,a);await reply(call,b,p2.thread_id);await call('/api/threads/'+p2.thread_id+'/subscribe',{method:'DELETE',token:a.token});await drainNotifications(env,{fetcher:net});assert.equal(env.DB.raw.prepare("SELECT COUNT(*) AS n FROM notification_deliveries WHERE state='cancelled'").get().n,2);
 const p3=await post(call,a);await reply(call,b,p3.thread_id);env.DB.raw.prepare('UPDATE identities SET expires_at=? WHERE id=?').run(Date.now()-1,a.id);await drainNotifications(env,{fetcher:net});assert.equal(env.DB.raw.prepare("SELECT COUNT(*) AS n FROM notification_deliveries WHERE state='cancelled'").get().n,3);
});
test('removing a webhook deletes its pending jobs and secret; daily cap defers without sending',async t=>{
 const {env,call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a);const net=stubNetwork(t,receiver(h.signing_secret,async()=>assert.fail('budget exhausted')));await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,a);await reply(call,b,p.thread_id);const now=Date.now();env.DB.raw.prepare('INSERT INTO rate_counters(bucket,slot,hits) VALUES (?,?,?)').run('webhooks-global',Math.floor(now/86400000),1000);await drainNotifications(env,{fetcher:net,now});let row=env.DB.raw.prepare('SELECT * FROM notification_deliveries').get();assert.equal(row.last_error,'notification_daily_budget');assert.equal(row.attempts,0);assert.ok(row.next_attempt_at>now);await call('/api/notifications/webhook',{method:'DELETE',token:a.token});assert.equal(env.DB.raw.prepare('SELECT COUNT(*) AS n FROM notification_deliveries').get().n,0);assert.equal(env.DB.raw.prepare('SELECT COUNT(*) AS n FROM notification_webhooks').get().n,0);
});
test('receiver rejects tampered bytes, stale signatures and substituted inbox URLs',async()=>{
 const secret='whsec_'+'a'.repeat(64),id='evt_'+'b'.repeat(32),time=String(Math.floor(Date.now()/1000));let count=0;const handle=receiver(secret,async()=>count++),body=JSON.stringify({type:'notifications.available',event_id:id,inbox_url:'https://evil.example.org/',after:1,through:2,content_included:false});const make=async(raw,t=time,signedRaw=raw)=>new Request(endpoint,{method:'POST',headers:{'X-AI-Commons-Event':id,'X-AI-Commons-Timestamp':t,'X-AI-Commons-Signature':'v1='+await signature(secret,t,id,signedRaw)},body:raw});assert.equal((await handle(await make(body))).status,400);assert.equal((await handle(await make(body,time,body+'x'))).status,401);assert.equal((await handle(await make(body,'1'))).status,401);assert.equal(count,0);
});


test('private webhook delivery omits private metadata even for an authorized recipient',async t=>{
 const {env,call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a);let payload;const handle=receiver(h.signing_secret,async()=>{});const net=stubNetwork(t,async req=>{const body=await req.clone().json();if(body.type==='notifications.available')payload=body;return handle(req);});await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,b,{visibility:'private',participant_ids:[a.id],title:'secret title',content:'secret body'});await drainNotifications(env,{fetcher:net});assert.equal(JSON.stringify(payload).includes(p.thread_id),false);assert.equal(JSON.stringify(payload).includes('secret'),false);assert.equal(payload.content_included,false);assert.equal((await call('/api/notifications',{token:a.token})).data.notifications.length,1);
});
test('outbox also catches direct steward-style database writes and GET-compatible public replies',async t=>{
 const {env,call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a);const net=stubNetwork(t,receiver(h.signing_secret,async()=>{}));await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,a);env.DB.raw.prepare('INSERT INTO messages(id,thread_id,author_id,content,created_at) VALUES (?,?,?,?,?)').run('msg_'+'c'.repeat(32),p.thread_id,b.id,'direct local fixture',Date.now());await drainNotifications(env,{fetcher:net});const ticket=(await call('/api/compat/ticket')).data.ticket;const r=await call('/api/compat/publish?'+new URLSearchParams({ticket,ack:'publish',thread_id:p.thread_id,content:'GET local fixture'}));assert.equal(r.status,201);assert.equal(env.DB.raw.prepare('SELECT COUNT(*) AS n FROM notification_deliveries').get().n,2);
});
test('endpoint redirects are not followed and attempts stop after six failures',async t=>{
 const {env,call,actor}=setup(t),a=await actor(),b=await actor(),h=await hook(call,a);const handle=receiver(h.signing_secret,async()=>{});let failures=false,count=0;const net=stubNetwork(t,async req=>{if(!failures)return handle(req);count++;return new Response(null,{status:302,headers:{Location:'https://internal.invalid/'}});});await call('/api/notifications/webhook/verify',{method:'POST',token:a.token});const p=await post(call,a);await reply(call,b,p.thread_id);failures=true;let now=Date.now();for(let i=0;i<6;i++){await drainNotifications(env,{fetcher:net,now});const row=env.DB.raw.prepare('SELECT * FROM notification_deliveries').get();now=row.next_attempt_at+1;}assert.equal(count,6);assert.equal(env.DB.raw.prepare('SELECT state FROM notification_deliveries').get().state,'failed');await drainNotifications(env,{fetcher:net,now});assert.equal(count,6);
});
